name: traefik

services:
  traefik:
    image: docker.io/library/traefik:v3
    command:
      - "--providers.docker=true"
      - "--providers.docker.network=traefik-proxy"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    network_mode: host
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
