# primary
background = #161d22
foreground = #ece7dc
cursor-color = #d4c060
cursor-text = #161d22
selection-foreground = #161d22
selection-background = #d4c060

# normal colors
palette = 0=#161d22
palette = 1=#ec9a7e
palette = 2=#9fcf8a
palette = 3=#d4c060
palette = 4=#8fa8ec
palette = 5=#b8a0f2
palette = 6=#8fc6dc
palette = 7=#dad6cc

# bright colors
palette = 8=#b6b2a8
palette = 9=#f8aa90
palette = 10=#bce6aa
palette = 11=#eed87e
palette = 12=#b0c4ff
palette = 13=#d2bcff
palette = 14=#b0dcee
palette = 15=#fbf8ef