background = rgba(22,29,34,1)
base = rgba(22,29,34,1)
alternate_base = rgba(22,29,34,1)

accent = rgba(212,192,96,1)
accent_secondary = rgba(184,160,242,1)

text = rgba(209,204,193,1)

font_family = Iosevka NFM
font_family_mono = JetBrainsMono NFM

h1_size = 19
h2_size = 15
h3_size = 13
font_size = 11
small_font_size = 10

rounding_large = 0
rounding_small = 0