foreground              #ece7dc
background              #161d22
selection_foreground    #161d22
selection_background    #d4c060
cursor                  #d4c060
cursor_text_color       #161d22

active_tab_foreground   #161d22
active_tab_background   #b8a0f2
inactive_tab_foreground #ece7dc
inactive_tab_background #232d34

# black
color0 #161d22
color8 #b6b2a8

# red
color1 #ec9a7e
color9 #f8aa90

# green
color2 #9fcf8a
color10 #bce6aa

# yellow
color3 #d4c060
color11 #eed87e

# blue
color4 #8fa8ec
color12 #b0c4ff

# magenta
color5 #b8a0f2
color13 #d2bcff

# cyan
color6 #8fc6dc
color14 #b0dcee

# white
color7 #dad6cc
color15 #fbf8ef