# primary
background = #191418
foreground = #eee0d1
cursor-color = #d0bce9
cursor-text = #191418
selection-foreground = #191418
selection-background = #b7a5cf

# normal colors
palette = 0=#191418
palette = 1=#e18e81
palette = 2=#b2bca0
palette = 3=#d9b785
palette = 4=#b7a5cf
palette = 5=#ca9fce
palette = 6=#a2bcb8
palette = 7=#dccbbc

# bright colors
palette = 8=#b8a8b1
palette = 9=#f1b2a1
palette = 10=#c9d1b7
palette = 11=#efd1a3
palette = 12=#d0bce9
palette = 13=#e3bde5
palette = 14=#bed5d0
palette = 15=#fff0e1