foreground              #eee0d1
background              #191418
selection_foreground    #191418
selection_background    #b7a5cf
cursor                  #d0bce9
cursor_text_color       #191418

active_tab_foreground   #191418
active_tab_background   #ca9fce
inactive_tab_foreground #eee0d1
inactive_tab_background #2d252e

# black
color0 #191418
color8 #b8a8b1

# red
color1 #e18e81
color9 #f1b2a1

# green
color2 #b2bca0
color10 #c9d1b7

# yellow
color3 #d9b785
color11 #efd1a3

# blue
color4 #b7a5cf
color12 #d0bce9

# magenta
color5 #ca9fce
color13 #e3bde5

# cyan
color6 #a2bcb8
color14 #bed5d0

# white
color7 #dccbbc
color15 #fff0e1