# primary
background = #121a2e
foreground = #f2ede0
cursor-color = #f0d050
cursor-text = #121a2e
selection-foreground = #121a2e
selection-background = #f0d050

# normal colors
palette = 0=#121a2e
palette = 1=#ef8e62
palette = 2=#8fcf6a
palette = 3=#f0d050
palette = 4=#86a8f4
palette = 5=#bca6ee
palette = 6=#9fd8e0
palette = 7=#ddd8cc

# bright colors
palette = 8=#bab6ac
palette = 9=#ffac86
palette = 10=#ace690
palette = 11=#fce67a
palette = 12=#aac2ff
palette = 13=#d6c2ff
palette = 14=#bfeaf0
palette = 15=#fffbf0