foreground              #f2ede0
background              #121a2e
selection_foreground    #121a2e
selection_background    #f0d050
cursor                  #f0d050
cursor_text_color       #121a2e

active_tab_foreground   #121a2e
active_tab_background   #bca6ee
inactive_tab_foreground #f2ede0
inactive_tab_background #1f2943

# black
color0 #121a2e
color8 #bab6ac

# red
color1 #ef8e62
color9 #ffac86

# green
color2 #8fcf6a
color10 #ace690

# yellow
color3 #f0d050
color11 #fce67a

# blue
color4 #86a8f4
color12 #aac2ff

# magenta
color5 #bca6ee
color13 #d6c2ff

# cyan
color6 #9fd8e0
color14 #bfeaf0

# white
color7 #ddd8cc
color15 #fffbf0