# primary
background = #17231f
foreground = #eee8db
cursor-color = #cedeaf
cursor-text = #17231f
selection-foreground = #17231f
selection-background = #b4ca9b

# normal colors
palette = 0=#17231f
palette = 1=#efa59a
palette = 2=#b4ca9b
palette = 3=#dfcb8d
palette = 4=#a6bdcd
palette = 5=#d7a8bd
palette = 6=#9dc8bf
palette = 7=#dad8cc

# bright colors
palette = 8=#afb7ac
palette = 9=#ffc1b4
palette = 10=#cedeaf
palette = 11=#f1dfa6
palette = 12=#c1d3e1
palette = 13=#efc4d6
palette = 14=#b8e0d5
palette = 15=#fff5e5