foreground              #eee8db
background              #17231f
selection_foreground    #17231f
selection_background    #b4ca9b
cursor                  #cedeaf
cursor_text_color       #17231f

active_tab_foreground   #17231f
active_tab_background   #d7a8bd
inactive_tab_foreground #eee8db
inactive_tab_background #2a3932

# black
color0 #17231f
color8 #afb7ac

# red
color1 #efa59a
color9 #ffc1b4

# green
color2 #b4ca9b
color10 #cedeaf

# yellow
color3 #dfcb8d
color11 #f1dfa6

# blue
color4 #a6bdcd
color12 #c1d3e1

# magenta
color5 #d7a8bd
color13 #efc4d6

# cyan
color6 #9dc8bf
color14 #b8e0d5

# white
color7 #dad8cc
color15 #fff5e5