# primary
background = #f6f3e9
foreground = #253b4b
cursor-color = #a12b51
cursor-text = #f6f3e9
selection-foreground = #f6f3e9
selection-background = #275f89

# normal colors
palette = 0=#253b4b
palette = 1=#a12b51
palette = 2=#1e6558
palette = 3=#805c21
palette = 4=#275f89
palette = 5=#6e4a82
palette = 6=#226775
palette = 7=#536571

# bright colors
palette = 8=#5b6f78
palette = 9=#ac3157
palette = 10=#236b5c
palette = 11=#856127
palette = 12=#286791
palette = 13=#76518a
palette = 14=#286d79
palette = 15=#253b4b