# primary
background = #1b1714
foreground = #eee6da
cursor-color = #c78cf4
cursor-text = #1b1714
selection-foreground = #1b1714
selection-background = #c78cf4

# normal colors
palette = 0=#1b1714
palette = 1=#f48a5c
palette = 2=#6fd0a8
palette = 3=#ecd06a
palette = 4=#8a9cfa
palette = 5=#c78cf4
palette = 6=#7fd0d0
palette = 7=#ddd4c8

# bright colors
palette = 8=#bdb2a5
palette = 9=#ffa98f
palette = 10=#aee6b6
palette = 11=#fbe38c
palette = 12=#b0c0ff
palette = 13=#dcb8ff
palette = 14=#a2e6e4
palette = 15=#fff6ea