# primary
background = #10201c
foreground = #f1ebdf
cursor-color = #f2a85a
cursor-text = #10201c
selection-foreground = #10201c
selection-background = #f2a85a

# normal colors
palette = 0=#10201c
palette = 1=#fa9478
palette = 2=#9ad488
palette = 3=#f2a85a
palette = 4=#92aef2
palette = 5=#e8a2b6
palette = 6=#66c6b0
palette = 7=#dcd6ca

# bright colors
palette = 8=#b9b4a9
palette = 9=#ffa48a
palette = 10=#a0e6b2
palette = 11=#ffc482
palette = 12=#b0c4ff
palette = 13=#ffbecf
palette = 14=#92e4da
palette = 15=#fdf9ee