foreground              #f1ebdf
background              #10201c
selection_foreground    #10201c
selection_background    #f2a85a
cursor                  #f2a85a
cursor_text_color       #10201c

active_tab_foreground   #10201c
active_tab_background   #e8a2b6
inactive_tab_foreground #f1ebdf
inactive_tab_background #1d312c

# black
color0 #10201c
color8 #b9b4a9

# red
color1 #fa9478
color9 #ffa48a

# green
color2 #9ad488
color10 #a0e6b2

# yellow
color3 #f2a85a
color11 #ffc482

# blue
color4 #92aef2
color12 #b0c4ff

# magenta
color5 #e8a2b6
color13 #ffbecf

# cyan
color6 #66c6b0
color14 #92e4da

# white
color7 #dcd6ca
color15 #fdf9ee