# primary
background = #1c1716
foreground = #efe6dc
cursor-color = #6fd39a
cursor-text = #1c1716
selection-foreground = #1c1716
selection-background = #6fd39a

# normal colors
palette = 0=#1c1716
palette = 1=#ec8a6c
palette = 2=#6fd39a
palette = 3=#e2b86a
palette = 4=#a2a6e4
palette = 5=#e59ab2
palette = 6=#7fcfc0
palette = 7=#ddd3c8

# bright colors
palette = 8=#b9afa5
palette = 9=#ffa88c
palette = 10=#94eab6
palette = 11=#f6d08e
palette = 12=#c0c4ff
palette = 13=#ffb8cc
palette = 14=#a2e6d8
palette = 15=#fff6ea