background = rgba(28,23,22,1)
base = rgba(28,23,22,1)
alternate_base = rgba(28,23,22,1)

accent = rgba(111,211,154,1)
accent_secondary = rgba(236,138,108,1)

text = rgba(212,202,191,1)

font_family = Iosevka NFM
font_family_mono = JetBrainsMono NFM

h1_size = 19
h2_size = 15
h3_size = 13
font_size = 11
small_font_size = 10

rounding_large = 0
rounding_small = 0