[colors.primary]
background = "#1b1519"
foreground = "#d2ccd2"

[colors.cursor]
cursor = "#e3a16f"
text = "#1b1519"

[colors.selection]
text = "#1b1519"
background = "#e3a16f"

[colors.normal]
black = "#2e2329"
red = "#cc5555"
green = "#96708e"
yellow = "#d7937d"
blue = "#6843ae"
magenta = "#63005A"
cyan = "#a46fd6"
white = "#d2ccd2"

[colors.bright]
black = "#42333b"
red = "#dd6666"
green = "#c7a3bf"
yellow = "#f4b39e"
blue = "#9877dc"
magenta = "#8a1a80"
cyan = "#dea6f5"
white = "#e8e8e8"