# primary
background = #1b1519
foreground = #d2ccd2
cursor-color = #e3a16f
cursor-text = #1b1519
selection-foreground = #1b1519
selection-background = #e3a16f

# normal colors
palette = 0=#2e2329
palette = 1=#cc5555
palette = 2=#96708e
palette = 3=#d7937d
palette = 4=#6843ae
palette = 5=#63005A
palette = 6=#a46fd6
palette = 7=#d2ccd2

# bright colors
palette = 8=#42333b
palette = 9=#dd6666
palette = 10=#c7a3bf
palette = 11=#f4b39e
palette = 12=#9877dc
palette = 13=#8a1a80
palette = 14=#dea6f5
palette = 15=#e8e8e8