background = rgba(27,21,25,1)
base = rgba(27,21,25,1)
alternate_base = rgba(27,21,25,1)

accent = rgba(99,0,90,1)
accent_secondary = rgba(164,111,214,1)

text = rgba(199,163,191,1)

font_family = Iosevka NFM
font_family_mono = JetBrainsMono NFM

h1_size = 19
h2_size = 15
h3_size = 13
font_size = 11
small_font_size = 10

rounding_large = 0
rounding_small = 0