foreground              #d2ccd2
background              #1b1519
selection_foreground    #1b1519
selection_background    #e3a16f
cursor                  #e3a16f
cursor_text_color       #1b1519

active_tab_foreground   #1b1519
active_tab_background   #63005A
inactive_tab_foreground #d2ccd2
inactive_tab_background #2f252c

# black
color0 #2e2329
color8 #42333b

# red
color1 #cc5555
color9 #dd6666

# green
color2 #96708e
color10 #c7a3bf

# yellow
color3 #d7937d
color11 #f4b39e

# blue
color4 #6843ae
color12 #9877dc

# magenta
color5 #63005A
color13 #8a1a80

# cyan
color6 #a46fd6
color14 #dea6f5

# white
color7 #d2ccd2
color15 #e8e8e8