Primary = "#8a1a80"
Subtle = "#642c9a"
Success = "#c7a3bf"
Error = "#cc5555"

Normal = "#d2ccd2"
Disabled = "#42333b"
Border = "#96708e"

SignalHigh = ["#dea6f5", "#dea6f5"]
SignalLow = ["#2e2329", "#2e2329"]

Saved = "#a46fd6"

TitleIcon = "󰖩 "
NetworkSecureIcon = "󰌾 "
NetworkOpenIcon = "󰿆 "
NetworkUnknownIcon = " "
NetworkSavedIcon = " "
