# primary
background = #121c1e
foreground = #f0ecdf
cursor-color = #88d84e
cursor-text = #121c1e
selection-foreground = #121c1e
selection-background = #88d84e

# normal colors
palette = 0=#121c1e
palette = 1=#f4983c
palette = 2=#88d84e
palette = 3=#e8d88a
palette = 4=#8aa6f2
palette = 5=#bcaaf0
palette = 6=#6cc4b0
palette = 7=#dcd8cc

# bright colors
palette = 8=#b8b5aa
palette = 9=#ffb466
palette = 10=#a8ec74
palette = 11=#f8eaaa
palette = 12=#acc0ff
palette = 13=#d4c4ff
palette = 14=#90dccc
palette = 15=#fcf9ee