foreground              #f0ecdf
background              #121c1e
selection_foreground    #121c1e
selection_background    #88d84e
cursor                  #88d84e
cursor_text_color       #121c1e

active_tab_foreground   #121c1e
active_tab_background   #bcaaf0
inactive_tab_foreground #f0ecdf
inactive_tab_background #1f2c2f

# black
color0 #121c1e
color8 #b8b5aa

# red
color1 #f4983c
color9 #ffb466

# green
color2 #88d84e
color10 #a8ec74

# yellow
color3 #e8d88a
color11 #f8eaaa

# blue
color4 #8aa6f2
color12 #acc0ff

# magenta
color5 #bcaaf0
color13 #d4c4ff

# cyan
color6 #6cc4b0
color14 #90dccc

# white
color7 #dcd8cc
color15 #fcf9ee