# primary
background = #18171f
foreground = #f1e8e2
cursor-color = #f28a72
cursor-text = #18171f
selection-foreground = #18171f
selection-background = #f28a72

# normal colors
palette = 0=#18171f
palette = 1=#f28a72
palette = 2=#8cc0a0
palette = 3=#f2b866
palette = 4=#86a4ee
palette = 5=#c4b2e0
palette = 6=#86c4d2
palette = 7=#ddd5cf

# bright colors
palette = 8=#bbb2ad
palette = 9=#ffaa94
palette = 10=#aad8bc
palette = 11=#ffd08c
palette = 12=#a8c0ff
palette = 13=#dccdf6
palette = 14=#a8dce8
palette = 15=#fff8f2