foreground              #f1e8e2
background              #18171f
selection_foreground    #18171f
selection_background    #f28a72
cursor                  #f28a72
cursor_text_color       #18171f

active_tab_foreground   #18171f
active_tab_background   #c4b2e0
inactive_tab_foreground #f1e8e2
inactive_tab_background #272631

# black
color0 #18171f
color8 #bbb2ad

# red
color1 #f28a72
color9 #ffaa94

# green
color2 #8cc0a0
color10 #aad8bc

# yellow
color3 #f2b866
color11 #ffd08c

# blue
color4 #86a4ee
color12 #a8c0ff

# magenta
color5 #c4b2e0
color13 #dccdf6

# cyan
color6 #86c4d2
color14 #a8dce8

# white
color7 #ddd5cf
color15 #fff8f2