# primary
background = #19151f
foreground = #f1e8dc
cursor-color = #ecc04a
cursor-text = #19151f
selection-foreground = #19151f
selection-background = #ecc04a

# normal colors
palette = 0=#19151f
palette = 1=#eb9a5c
palette = 2=#a8c890
palette = 3=#ecc04a
palette = 4=#9ea6ec
palette = 5=#bd96ee
palette = 6=#8cc8c4
palette = 7=#ddd2c6

# bright colors
palette = 8=#bbb1aa
palette = 9=#ffb48e
palette = 10=#c2dfaa
palette = 11=#ffd874
palette = 12=#bec4ff
palette = 13=#dcc0ff
palette = 14=#ade0dc
palette = 15=#fff4e8