foreground              #f1e8dc
background              #19151f
selection_foreground    #19151f
selection_background    #ecc04a
cursor                  #ecc04a
cursor_text_color       #19151f

active_tab_foreground   #19151f
active_tab_background   #bd96ee
inactive_tab_foreground #f1e8dc
inactive_tab_background #27212f

# black
color0 #19151f
color8 #bbb1aa

# red
color1 #eb9a5c
color9 #ffb48e

# green
color2 #a8c890
color10 #c2dfaa

# yellow
color3 #ecc04a
color11 #ffd874

# blue
color4 #9ea6ec
color12 #bec4ff

# magenta
color5 #bd96ee
color13 #dcc0ff

# cyan
color6 #8cc8c4
color14 #ade0dc

# white
color7 #ddd2c6
color15 #fff4e8