background = rgba(40,40,40,1)
base = rgba(40,40,40,1)
alternate_base = rgba(40,40,40,1)

accent = rgba(231,138,78,1)
accent_secondary = rgba(125,174,163,1)

text = rgba(169,182,101,1)

font_family = Iosevka NFM
font_family_mono = JetBrainsMono NFM

h1_size = 19
h2_size = 15
h3_size = 13
font_size = 11
small_font_size = 10

rounding_large = 0
rounding_small = 0