# primary
background = #15161d
foreground = #efe9e2
cursor-color = #f286c6
cursor-text = #15161d
selection-foreground = #15161d
selection-background = #f286c6

# normal colors
palette = 0=#15161d
palette = 1=#f48a8e
palette = 2=#6fd2a2
palette = 3=#ecd06a
palette = 4=#8a9df4
palette = 5=#f286c6
palette = 6=#7fcfd8
palette = 7=#ddd7cf

# bright colors
palette = 8=#b9b4ae
palette = 9=#ff9ea0
palette = 10=#94eabe
palette = 11=#fae48e
palette = 12=#acbaff
palette = 13=#ffb0d8
palette = 14=#a2e6ec
palette = 15=#fffaf3