foreground              #efe9e2
background              #15161d
selection_foreground    #15161d
selection_background    #f286c6
cursor                  #f286c6
cursor_text_color       #15161d

active_tab_foreground   #15161d
active_tab_background   #f286c6
inactive_tab_foreground #efe9e2
inactive_tab_background #24252f

# black
color0 #15161d
color8 #b9b4ae

# red
color1 #f48a8e
color9 #ff9ea0

# green
color2 #6fd2a2
color10 #94eabe

# yellow
color3 #ecd06a
color11 #fae48e

# blue
color4 #8a9df4
color12 #acbaff

# magenta
color5 #f286c6
color13 #ffb0d8

# cyan
color6 #7fcfd8
color14 #a2e6ec

# white
color7 #ddd7cf
color15 #fffaf3