# primary
background = #141b17
foreground = #f1ebdd
cursor-color = #fa866e
cursor-text = #141b17
selection-foreground = #141b17
selection-background = #fa866e

# normal colors
palette = 0=#141b17
palette = 1=#fa866e
palette = 2=#74c97e
palette = 3=#e8c27a
palette = 4=#9ab4e0
palette = 5=#e6a0b0
palette = 6=#86c8c0
palette = 7=#ddd7ca

# bright colors
palette = 8=#b9b4a8
palette = 9=#ffa28c
palette = 10=#aee6a8
palette = 11=#f8d89c
palette = 12=#b8ccf6
palette = 13=#ffbccb
palette = 14=#a8e0d8
palette = 15=#fdf9ee