background = rgba(20,27,23,1)
base = rgba(20,27,23,1)
alternate_base = rgba(20,27,23,1)

accent = rgba(250,134,110,1)
accent_secondary = rgba(116,201,126,1)

text = rgba(213,207,194,1)

font_family = Iosevka NFM
font_family_mono = JetBrainsMono NFM

h1_size = 19
h2_size = 15
h3_size = 13
font_size = 11
small_font_size = 10

rounding_large = 0
rounding_small = 0