foreground              #f1ebdd
background              #141b17
selection_foreground    #141b17
selection_background    #fa866e
cursor                  #fa866e
cursor_text_color       #141b17

active_tab_foreground   #141b17
active_tab_background   #e6a0b0
inactive_tab_foreground #f1ebdd
inactive_tab_background #212b25

# black
color0 #141b17
color8 #b9b4a8

# red
color1 #fa866e
color9 #ffa28c

# green
color2 #74c97e
color10 #aee6a8

# yellow
color3 #e8c27a
color11 #f8d89c

# blue
color4 #9ab4e0
color12 #b8ccf6

# magenta
color5 #e6a0b0
color13 #ffbccb

# cyan
color6 #86c8c0
color14 #a8e0d8

# white
color7 #ddd7ca
color15 #fdf9ee