# primary
background = #19272b
foreground = #f1e7d5
cursor-color = #dfbb72
cursor-text = #19272b
selection-foreground = #19272b
selection-background = #dfbb72

# normal colors
palette = 0=#19272b
palette = 1=#e7afa5
palette = 2=#b1c8a0
palette = 3=#dfbb72
palette = 4=#acc3db
palette = 5=#d6b0c9
palette = 6=#a1c9c4
palette = 7=#d9d0bd

# bright colors
palette = 8=#bdc0b5
palette = 9=#f4c5bc
palette = 10=#c8dbb8
palette = 11=#f0d395
palette = 12=#c4d8ea
palette = 13=#e9c7df
palette = 14=#bee0d8
palette = 15=#fff6e6