foreground              #f1e7d5
background              #19272b
selection_foreground    #19272b
selection_background    #dfbb72
cursor                  #dfbb72
cursor_text_color       #19272b

active_tab_foreground   #19272b
active_tab_background   #d6b0c9
inactive_tab_foreground #f1e7d5
inactive_tab_background #29383e

# black
color0 #19272b
color8 #bdc0b5

# red
color1 #e7afa5
color9 #f4c5bc

# green
color2 #b1c8a0
color10 #c8dbb8

# yellow
color3 #dfbb72
color11 #f0d395

# blue
color4 #acc3db
color12 #c4d8ea

# magenta
color5 #d6b0c9
color13 #e9c7df

# cyan
color6 #a1c9c4
color14 #bee0d8

# white
color7 #d9d0bd
color15 #fff6e6