# primary
background = #212518
foreground = #f6e8c5
cursor-color = #edc565
cursor-text = #212518
selection-foreground = #212518
selection-background = #edc565

# normal colors
palette = 0=#212518
palette = 1=#efa387
palette = 2=#b4ce86
palette = 3=#edc565
palette = 4=#a9b9e9
palette = 5=#dca8d2
palette = 6=#94cbc0
palette = 7=#e4d6b7

# bright colors
palette = 8=#bec1a6
palette = 9=#ffc3a6
palette = 10=#cce5a5
palette = 11=#ffdf88
palette = 12=#c4cef8
palette = 13=#f0c4e5
palette = 14=#b6e4d7
palette = 15=#fff5dc