background = rgba(33,37,24,1)
base = rgba(33,37,24,1)
alternate_base = rgba(33,37,24,1)

accent = rgba(237,197,101,1)
accent_secondary = rgba(239,163,135,1)

text = rgba(216,205,178,1)

font_family = Iosevka NFM
font_family_mono = JetBrainsMono NFM

h1_size = 19
h2_size = 15
h3_size = 13
font_size = 11
small_font_size = 10

rounding_large = 0
rounding_small = 0