foreground              #f6e8c5
background              #212518
selection_foreground    #212518
selection_background    #edc565
cursor                  #edc565
cursor_text_color       #212518

active_tab_foreground   #212518
active_tab_background   #dca8d2
inactive_tab_foreground #f6e8c5
inactive_tab_background #303624

# black
color0 #212518
color8 #bec1a6

# red
color1 #efa387
color9 #ffc3a6

# green
color2 #b4ce86
color10 #cce5a5

# yellow
color3 #edc565
color11 #ffdf88

# blue
color4 #a9b9e9
color12 #c4cef8

# magenta
color5 #dca8d2
color13 #f0c4e5

# cyan
color6 #94cbc0
color14 #b6e4d7

# white
color7 #e4d6b7
color15 #fff5dc