# primary
background = #1d1a17
foreground = #efe7da
cursor-color = #c194f2
cursor-text = #1d1a17
selection-foreground = #1d1a17
selection-background = #c194f2

# normal colors
palette = 0=#1d1a17
palette = 1=#f2a084
palette = 2=#86d686
palette = 3=#e4c56a
palette = 4=#8ea4f4
palette = 5=#c194f2
palette = 6=#96dcc4
palette = 7=#ddd5c8

# bright colors
palette = 8=#b9b0a2
palette = 9=#ffbca2
palette = 10=#a8ecaa
palette = 11=#f8dc8e
palette = 12=#b0c0ff
palette = 13=#d8b4ff
palette = 14=#b6f0dc
palette = 15=#fff7ea