background = rgba(29,26,23,1)
base = rgba(29,26,23,1)
alternate_base = rgba(29,26,23,1)

accent = rgba(193,148,242,1)
accent_secondary = rgba(150,220,196,1)

text = rgba(212,203,189,1)

font_family = Iosevka NFM
font_family_mono = JetBrainsMono NFM

h1_size = 19
h2_size = 15
h3_size = 13
font_size = 11
small_font_size = 10

rounding_large = 0
rounding_small = 0