foreground              #efe7da
background              #1d1a17
selection_foreground    #1d1a17
selection_background    #c194f2
cursor                  #c194f2
cursor_text_color       #1d1a17

active_tab_foreground   #1d1a17
active_tab_background   #c194f2
inactive_tab_foreground #efe7da
inactive_tab_background #2c2722

# black
color0 #1d1a17
color8 #b9b0a2

# red
color1 #f2a084
color9 #ffbca2

# green
color2 #86d686
color10 #a8ecaa

# yellow
color3 #e4c56a
color11 #f8dc8e

# blue
color4 #8ea4f4
color12 #b0c0ff

# magenta
color5 #c194f2
color13 #d8b4ff

# cyan
color6 #96dcc4
color14 #b6f0dc

# white
color7 #ddd5c8
color15 #fff7ea