# primary
background = #15191a
foreground = #efe9e0
cursor-color = #f28a64
cursor-text = #15191a
selection-foreground = #15191a
selection-background = #f28a64

# normal colors
palette = 0=#15191a
palette = 1=#f28a64
palette = 2=#b2bc92
palette = 3=#d8bc7a
palette = 4=#8aa6f0
palette = 5=#d8a6bc
palette = 6=#9cc0cc
palette = 7=#dcd6cd

# bright colors
palette = 8=#b8b4ac
palette = 9=#ffa886
palette = 10=#c2dab6
palette = 11=#f4d692
palette = 12=#acc0ff
palette = 13=#f0c2d4
palette = 14=#bcd8e2
palette = 15=#fcf8f0