foreground              #efe9e0
background              #15191a
selection_foreground    #15191a
selection_background    #f28a64
cursor                  #f28a64
cursor_text_color       #15191a

active_tab_foreground   #15191a
active_tab_background   #d8a6bc
inactive_tab_foreground #efe9e0
inactive_tab_background #222829

# black
color0 #15191a
color8 #b8b4ac

# red
color1 #f28a64
color9 #ffa886

# green
color2 #b2bc92
color10 #c2dab6

# yellow
color3 #d8bc7a
color11 #f4d692

# blue
color4 #8aa6f0
color12 #acc0ff

# magenta
color5 #d8a6bc
color13 #f0c2d4

# cyan
color6 #9cc0cc
color14 #bcd8e2

# white
color7 #dcd6cd
color15 #fcf8f0