# primary
background = {{base.background}}
foreground = {{base.foreground}}
cursor-color = {{ui.cursor}}
cursor-text = {{base.background}}
selection-foreground = {{ui.selection_fg}}
selection-background = {{ui.selection_bg}}

# normal colors
palette = 0={{ansi.black}}
palette = 1={{ansi.red}}
palette = 2={{ansi.green}}
palette = 3={{ansi.yellow}}
palette = 4={{ansi.blue}}
palette = 5={{ansi.magenta}}
palette = 6={{ansi.cyan}}
palette = 7={{ansi.white}}

# bright colors
palette = 8={{bright.black}}
palette = 9={{bright.red}}
palette = 10={{bright.green}}
palette = 11={{bright.yellow}}
palette = 12={{bright.blue}}
palette = 13={{bright.magenta}}
palette = 14={{bright.cyan}}
palette = 15={{bright.white}}
