# primary
background = #1a1c26
foreground = #f4ecdc
cursor-color = #f4a83c
cursor-text = #1a1c26
selection-foreground = #1a1c26
selection-background = #f4a83c

# normal colors
palette = 0=#1a1c26
palette = 1=#f79478
palette = 2=#a6d06a
palette = 3=#f4a83c
palette = 4=#8ab4f0
palette = 5=#ef9ac4
palette = 6=#7fcfd2
palette = 7=#e2dacb

# bright colors
palette = 8=#bcb6aa
palette = 9=#ffa98c
palette = 10=#c2e68e
palette = 11=#ffc46a
palette = 12=#acccff
palette = 13=#ffb8d8
palette = 14=#a2e6e6
palette = 15=#fffaef