foreground              #f4ecdc
background              #1a1c26
selection_foreground    #1a1c26
selection_background    #f4a83c
cursor                  #f4a83c
cursor_text_color       #1a1c26

active_tab_foreground   #1a1c26
active_tab_background   #ef9ac4
inactive_tab_foreground #f4ecdc
inactive_tab_background #292d3b

# black
color0 #1a1c26
color8 #bcb6aa

# red
color1 #f79478
color9 #ffa98c

# green
color2 #a6d06a
color10 #c2e68e

# yellow
color3 #f4a83c
color11 #ffc46a

# blue
color4 #8ab4f0
color12 #acccff

# magenta
color5 #ef9ac4
color13 #ffb8d8

# cyan
color6 #7fcfd2
color14 #a2e6e6

# white
color7 #e2dacb
color15 #fffaef