# primary
background = #1f1714
foreground = #f3e8d8
cursor-color = #f3a64a
cursor-text = #1f1714
selection-foreground = #1f1714
selection-background = #f3a64a

# normal colors
palette = 0=#1f1714
palette = 1=#f28462
palette = 2=#a6cf7a
palette = 3=#f3a64a
palette = 4=#93a8d4
palette = 5=#e6a0b6
palette = 6=#6fc8b8
palette = 7=#e0d4c4

# bright colors
palette = 8=#bcb0a2
palette = 9=#ffa486
palette = 10=#c2e69c
palette = 11=#ffc072
palette = 12=#b0c6ff
palette = 13=#ffbed0
palette = 14=#92e2d2
palette = 15=#fff6e8