foreground              #f3e8d8
background              #1f1714
selection_foreground    #1f1714
selection_background    #f3a64a
cursor                  #f3a64a
cursor_text_color       #1f1714

active_tab_foreground   #1f1714
active_tab_background   #e6a0b6
inactive_tab_foreground #f3e8d8
inactive_tab_background #2e241f

# black
color0 #1f1714
color8 #bcb0a2

# red
color1 #f28462
color9 #ffa486

# green
color2 #a6cf7a
color10 #c2e69c

# yellow
color3 #f3a64a
color11 #ffc072

# blue
color4 #93a8d4
color12 #b0c6ff

# magenta
color5 #e6a0b6
color13 #ffbed0

# cyan
color6 #6fc8b8
color14 #92e2d2

# white
color7 #e0d4c4
color15 #fff6e8