foreground              #edeade
background              #141e2a
selection_foreground    #141e2a
selection_background    #86b6db
cursor                  #ef7c9c
cursor_text_color       #141e2a

active_tab_foreground   #141e2a
active_tab_background   #b4a0d4
inactive_tab_foreground #edeade
inactive_tab_background #263747

# black
color0 #141e2a
color8 #90a4b2

# red
color1 #ef7c9c
color9 #ff9bb5

# green
color2 #82bfaa
color10 #a4d5bd

# yellow
color3 #e6cf8d
color11 #f3dfaa

# blue
color4 #86b6db
color12 #a3cdf0

# magenta
color5 #b4a0d4
color13 #d0bde8

# cyan
color6 #83c6cb
color14 #a2dde0

# white
color7 #c8d4db
color15 #f6f3e9