# primary
background = #141c1b
foreground = #efeadc
cursor-color = #98a6f6
cursor-text = #141c1b
selection-foreground = #141c1b
selection-background = #98a6f6

# normal colors
palette = 0=#141c1b
palette = 1=#ee9670
palette = 2=#88c4aa
palette = 3=#f2a65a
palette = 4=#98a6f6
palette = 5=#b89af0
palette = 6=#7fc8b8
palette = 7=#dcd8cb

# bright colors
palette = 8=#b8b5a8
palette = 9=#ffb292
palette = 10=#aadfb6
palette = 11=#ffc082
palette = 12=#b2bcff
palette = 13=#d2b8ff
palette = 14=#a0e0d2
palette = 15=#fcf8ec