foreground              #efeadc
background              #141c1b
selection_foreground    #141c1b
selection_background    #98a6f6
cursor                  #98a6f6
cursor_text_color       #141c1b

active_tab_foreground   #141c1b
active_tab_background   #b89af0
inactive_tab_foreground #efeadc
inactive_tab_background #212c2b

# black
color0 #141c1b
color8 #b8b5a8

# red
color1 #ee9670
color9 #ffb292

# green
color2 #88c4aa
color10 #aadfb6

# yellow
color3 #f2a65a
color11 #ffc082

# blue
color4 #98a6f6
color12 #b2bcff

# magenta
color5 #b89af0
color13 #d2b8ff

# cyan
color6 #7fc8b8
color14 #a0e0d2

# white
color7 #dcd8cb
color15 #fcf8ec