foreground              #d3c6aa
background              #2d353b
selection_foreground    #9da9a0
selection_background    #505A60
cursor                  #d3c6aa
cursor_text_color       #2d353b

active_tab_foreground   #2d353b
active_tab_background   #d699b6
inactive_tab_foreground #d3c6aa
inactive_tab_background #3D484D

# black
color0 #343f44
color8 #868d80

# red
color1 #e67e80
color9 #e67e80

# green
color2 #a7c080
color10 #a7c080

# yellow
color3 #dbbc7f
color11 #dbbc7f

# blue
color4 #7fbbb3
color12 #7fbbb3

# magenta
color5 #d699b6
color13 #d699b6

# cyan
color6 #83c092
color14 #83c092

# white
color7 #859289
color15 #9da9a0