Primary = "#a7c080"
Subtle = "#417a72"
Success = "#a7c080"
Error = "#e67e80"

Normal = "#d3c6aa"
Disabled = "#868d80"
Border = "#56635F"

SignalHigh = ["#83c092", "#83c092"]
SignalLow = ["#343f44", "#343f44"]

Saved = "#83c092"

TitleIcon = "󰖩 "
NetworkSecureIcon = "󰌾 "
NetworkOpenIcon = "󰿆 "
NetworkUnknownIcon = " "
NetworkSavedIcon = " "
