[mgr]
cwd = { fg = "#7fbbb3" }

find_keyword  = { fg = "#a7c080", bold = true }
find_position = { fg = "#7fbbb3", bold = true }

marker_copied   = { fg = "#a7c080", bg = "#a7c080" }
marker_cut      = { fg = "#e67e80", bg = "#e67e80" }
marker_marked   = { fg = "#7fbbb3", bg = "#7fbbb3" }
marker_selected = { fg = "#dbbc7f", bg = "#dbbc7f" }

border_style = { fg = "#a7c080" }

syntect_theme = ""

# Tabs
[tabs]
sep_outer = { open = "", close = "" }
sep_inner = { open = "", close = "" }

active   = { bg = "#7fbbb3", fg = "#2d353b", bold = true }
inactive = { fg = "#7fbbb3", bg = "#343F44" }

# Mode
[mode]
normal_main = { bg = "#7fbbb3", fg = "#2d353b", bold = true }
normal_alt  = { fg = "#7fbbb3", bg = "#343F44" }

select_main = { bg = "#a7c080", fg = "#2d353b", bold = true }
select_alt  = { fg = "#a7c080", bg = "#343F44" }

unset_main = { bg = "#e67e80", fg = "#2d353b", bold = true }
unset_alt  = { fg = "#e67e80", bg = "#343F44" }

# Status
[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

perm_sep   = { fg = "#7A8478" }
perm_type  = { fg = "#a7c080" }
perm_read  = { fg = "#dbbc7f" }
perm_write = { fg = "#e67e80" }
perm_exec  = { fg = "#7fbbb3" }

progress_normal = { fg = "#a7c080", bg = "#3D484D" }
progress_error  = { fg = "#dbbc7f", bg = "#e67e80" }

# Which menu
[which]
mask = { bg = "#2d353b" }
cand = { fg = "#7fbbb3" }
rest = { fg = "#7A8478" }
desc = { fg = "#a7c080" }

# Confirm
[confirm]
border = { fg = "#7fbbb3" }
title  = { fg = "#7fbbb3" }

# Notifications
[notify]
title_info  = { fg = "#a7c080" }
title_warn  = { fg = "#dbbc7f" }
title_error = { fg = "#e67e80" }

# Picker
[pick]
border = { fg = "#7fbbb3" }
active = { fg = "#a7c080", bold = true }

# Input
[input]
border = { fg = "#7fbbb3" }

# Completion
[cmp]
border = { fg = "#7fbbb3" }

# Tasks
[tasks]
border  = { fg = "#7fbbb3" }
hovered = { fg = "#a7c080", bold = true }

# Help
[help]
on      = { fg = "#7fbbb3" }
run     = { fg = "#a7c080" }
desc    = { fg = "#d3c6aa" }
footer  = { fg = "#2d353b", bg = "#d3c6aa" }

# Filetypes
[filetype]
rules = [
  { mime = "image/*", fg = "#dbbc7f" },
  { mime = "{audio,video}/*", fg = "#a7c080" },
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma}", fg = "#e67e80" },
  { mime = "application/{pdf,doc,rtf}", fg = "#7fbbb3" },
  { url = "*", is = "exec", fg = "#a7c080" },
  { url = "*/", fg = "#7fbbb3" }
]

# Indicator
[indicator]
padding = { open = "█", close = "█" }