# primary
background = #151a2a
foreground = #f3ebe6
cursor-color = #86a8f6
cursor-text = #151a2a
selection-foreground = #151a2a
selection-background = #86a8f6

# normal colors
palette = 0=#151a2a
palette = 1=#f48e70
palette = 2=#92d27c
palette = 3=#f0d468
palette = 4=#86a8f6
palette = 5=#f0a8c0
palette = 6=#6fd0d8
palette = 7=#e0d8d3

# bright colors
palette = 8=#bcb6b2
palette = 9=#ffac92
palette = 10=#b0e89c
palette = 11=#fce88c
palette = 12=#aac2ff
palette = 13=#ffc4d6
palette = 14=#94e6ec
palette = 15=#fffaf6