foreground              #f3ebe6
background              #151a2a
selection_foreground    #151a2a
selection_background    #86a8f6
cursor                  #86a8f6
cursor_text_color       #151a2a

active_tab_foreground   #151a2a
active_tab_background   #f0a8c0
inactive_tab_foreground #f3ebe6
inactive_tab_background #22293e

# black
color0 #151a2a
color8 #bcb6b2

# red
color1 #f48e70
color9 #ffac92

# green
color2 #92d27c
color10 #b0e89c

# yellow
color3 #f0d468
color11 #fce88c

# blue
color4 #86a8f6
color12 #aac2ff

# magenta
color5 #f0a8c0
color13 #ffc4d6

# cyan
color6 #6fd0d8
color14 #94e6ec

# white
color7 #e0d8d3
color15 #fffaf6