name: kiwix

services:
  kiwix:
    image: ghcr.io/kiwix/kiwix-serve:latest
    volumes:
      - ./data:/data
    ports:
      - "127.0.0.1:8888:8080"
    command: "*.zim"
    restart: unless-stopped
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kiwix.rule=Host(`kiwix.local`)"
      - "traefik.http.routers.kiwix.entrypoints=web"
      - "traefik.http.services.kiwix.loadbalancer.server.port=8080"

networks:
  traefik-proxy:
    external: true
