# primary
background = #171a24
foreground = #f3ead6
cursor-color = #f2cd4a
cursor-text = #171a24
selection-foreground = #171a24
selection-background = #f2cd4a

# normal colors
palette = 0=#171a24
palette = 1=#f7926a
palette = 2=#9fd08a
palette = 3=#f2cd4a
palette = 4=#97adf4
palette = 5=#eaa0c0
palette = 6=#6ec4c8
palette = 7=#e0d8c6

# bright colors
palette = 8=#bdb7a8
palette = 9=#ffa890
palette = 10=#bce6a8
palette = 11=#ffe27a
palette = 12=#b0c2ff
palette = 13=#ffbfd9
palette = 14=#9de6dd
palette = 15=#fffaec