foreground              #f3ead6
background              #171a24
selection_foreground    #171a24
selection_background    #f2cd4a
cursor                  #f2cd4a
cursor_text_color       #171a24

active_tab_foreground   #171a24
active_tab_background   #eaa0c0
inactive_tab_foreground #f3ead6
inactive_tab_background #262b3a

# black
color0 #171a24
color8 #bdb7a8

# red
color1 #f7926a
color9 #ffa890

# green
color2 #9fd08a
color10 #bce6a8

# yellow
color3 #f2cd4a
color11 #ffe27a

# blue
color4 #97adf4
color12 #b0c2ff

# magenta
color5 #eaa0c0
color13 #ffbfd9

# cyan
color6 #6ec4c8
color14 #9de6dd

# white
color7 #e0d8c6
color15 #fffaec